from . import (
    exporter_apickli,
    exporter_confluence,
    exporter_curl,
    exporter_java_feign_client,
    exporter_locust_tests,
    exporter_markdown,
    exporter_mermaid,
    exporter_openapi_v3,
    exporter_plantuml,
    exporter_python_requests,
    exporter_restassured,
    exporter_runscope,
    exporter_slow_cooker,
    exporter_spring_boot_api_java,
    exporter_spring_contract_tests,
)

exporter_plugins = {
    "locust": exporter_locust_tests,
    "confluence": exporter_confluence,
    "runscope": exporter_runscope,
    "apickli": exporter_apickli,
    "slow_cooker": exporter_slow_cooker,
    "plant_uml": exporter_plantuml,
    "python_requests": exporter_python_requests,
    "curl": exporter_curl,
    "markdown": exporter_markdown,
    "mermaid": exporter_mermaid,
    "openapi_v3": exporter_openapi_v3,
    "restassured": exporter_restassured,
    "spring_contract_tests": exporter_spring_contract_tests,
    "spring_boot_api_java": exporter_spring_boot_api_java,
    "java_feign_client": exporter_java_feign_client,
}
